### ISSUE TITLE
Add Gateway setup documentation in Getting Started wiki

### ISSUE THREAD

**Issue by anirudhTiwari20** [dhp-project/DHP-Specs#19]

**Comment by core-wg-admin** [comment]
@anirudhTiwari20 Gateway is independent of use case.

**Comment by core-wg-admin** [comment]
Editing the title from `Add Gateway setup documentation in Getting Started wiki for Ambulance Booking` to `Add Gateway setup documentation in Getting Started wiki`

**Comment by core-wg-admin** [comment]
Gateway setup is any ways generic and does not need a separate documentation. So closing this.
